language: node_js
node_js:
  - 12
  - 13
install:
  - npm ci
script:
  - npm run build
  - git status
  - bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes in webpack build' && exit 1 )"
